# Generated by Django 3.2.8 on 2021-11-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='link',
            new_name='historyLink',
        ),
    ]
