# Generated by Django 3.2.8 on 2021-11-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_link_history_historylink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='historyLink',
            field=models.CharField(max_length=45),
        ),
    ]
